mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
secret: ''

proxy-providers:
  SUb:
    type: http
    url: $url
    interval: 7200
    path: ./Proxy/Sub.yaml
    health-check:
      enable: true
      interval: 300
      url: http://www.gstatic.com/generate_204

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - Auto-test
    use:
      - Sub

  - name: Others
    type: select
    proxies:
      - Proxy
      - DIRECT

  - name: Auto-test
    type: url-test
    use:
      - Sub
    url: http://www.gstatic.com/generate_204
    interval: 300

  - name: Global
    type: select
    proxies:
      - Proxy
      - DIRECT
    use:
      - Sub

  - name: China
    type: select
    proxies:
      - DIRECT
      - Proxy

  - name: PayPal
    type: select
    proxies:
      - DIRECT
      - Proxy
  
  - name: Scholar
    type: select
    proxies:
      - DIRECT
      - Proxy

  - name: Telegram
    type: select
    proxies:
      - Proxy
      - DIRECT
    use:
      - Sub

  - name: Apple
    type: select
    proxies:
      - DIRECT
      - Proxy
    use:
      - Sub
  - name: Steam
    type: select
    proxies:
      - DIRECT
      - Proxy
    use:
      - Sub

  - name: OneDrive
    type: select
    proxies:
      - Proxy
      - DIRECT
    use:
      - Sub

  - name: Streaming
    type: select
    proxies:
      - Proxy
      - DIRECT
    use:
      - Sub

rule-providers:

  Global:
    type: http
    behavior: classical
    path: ./RuleSet/Global.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Global.yaml
    interval: 86400

  China:
    type: http
    behavior: classical
    path: ./RuleSet/China.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml
    interval: 86400

  ChinaIP:
    type: http
    behavior: ipcidr
    path: ./RuleSet/Extra/ChinaIP.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/ChinaIP.yaml
    interval: 86400

  PayPal:
    type: http
    behavior: classical
    path: ./RuleSet/Extra/PayPal.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/PayPal.yaml
    interval: 86400

  Scholar:
    type: http
    behavior: classical
    path: ./RuleSet/Extra/Scholar.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Scholar.yaml
    interval: 86400

  Telegram:
    type: http
    behavior: classical
    path: ./RuleSet/Extra/Telegram/Telegram.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Telegram/Telegram.yaml
    interval: 86400

  Apple:
    type: http
    behavior: classical
    path: ./RuleSet/Extra/Apple/Apple.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Apple/Apple.yaml
    interval: 86400
  
  Steam:
    type: http
    behavior: classical
    path: ./RuleSet/Extra/Game/Steam.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Game/Steam.yaml
    interval: 86400

  OneDrive:
    type: http
    behavior: classical
    path: ./RuleSet/Extra/Microsoft/OneDrive.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Microsoft/OneDrive.yaml
    interval: 86400

  Streaming:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/Streaming.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Streaming.yaml
    interval: 86400

# 规则
rules:
  - RULE-SET,Apple,Apple
  - RULE-SET,OneDrive,OneDrive
  - RULE-SET,PayPal,PayPal
  - RULE-SET,Scholar,Scholar
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Steam,Steam
  - RULE-SET,Streaming,Streaming
  - RULE-SET,Global,Global
  - RULE-SET,China,China

  # Local Area Network
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT

  # ChinaIP
  - RULE-SET,ChinaIP,China

  # Final
  - MATCH,Others